version: "3.6"
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
      - "5673:5672"
      - "15673:15672"
  postgres:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=Password12!"
    ports:
      - 5432:5432
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
  api:
    image: sample/api
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=host=postgres;user id=postgres;password=Password12!;database=Outbox;
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger:5778/sampling
    build:
      context: ./src
      dockerfile: Dockerfile.api
    ports:
     - "5000:80"
  service:
    image: sample/worker
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=host=postgres;user id=postgres;password=Password12!;database=Outbox;
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=remote
      - JAEGER_SAMPLING_ENDPOINT=http://jaeger:5778/sampling
    build:
      context: ./src
      dockerfile: Dockerfile.worker
